### ISSUE TITLE
Remove extra non-letter chars

### ISSUE THREAD

**Issue by Gabrielsonnn** [Gabrielsonnn/Intervocalic-t-Search#2]

**Comment by allyugalde** [comment]
Ignore: [everything inside], {everything inside}

You may come across ? and ., these punctuation marks will always be surrounded by spaces " ? " and " . ". Try not to have them included in the output.

Lastly (**new note**): words which are not complete appear as the following (part of word that's spoken immediately (no spaces) followed by two dashes and a space, then continuing the transcription):
`I went to the amus-- I mean the zoo`
If the word has a `--`, include it in the word.

**Comment by Gabrielsonnn** [comment]
if ch == ',' or ch == '.' or ch == '!' or ch == '?' or ch == '/' or ch == ';' or ch == ':' or ch == '(' or ch == ")" or ch == '<' or ch == '>':

These are all the extra characters I'm checking for and removing. Is this good enough?

**Comment by allyugalde** [comment]
Text within <> brackets are called **back-channel cues**. These are background vocals made by other speakers such as `<mm-hm>` and `<okay>`.

There is a finite list of back-channel cues allowed in transcription, and none of them should have "t" or intervocalic "t". You can choose to let the loop run through it to search for "t" or skip over it, as it shouldn't produce any output anyways.

**Comment by allyugalde** [comment]
> if ch == ',' or ch == '.' or ch == '!' or ch == '?' or ch == '/' or ch == ';' or ch == ':' or ch == '(' or ch == ")" or ch == '<' or ch == '>':
> 
> These are all the extra characters I'm checking for and removing. Is this good enough?

That looks good. There are no '!', ':', or ';' (except ':' in the timestamps).
