### ISSUE TITLE
Ignore transcribers notes

### ISSUE THREAD

**Issue by Gabrielsonnn** [Gabrielsonnn/Intervocalic-t-Search#5]
Not fully sure how to deal with this, more information is required.

**Comment by allyugalde** [comment]
An example of what the notes look like:

`M021    can you please get your lunch boxes ?`
`        00:00:00.000 - 00:00:01.002`

`Notes   The mics are very quiet and it's sometimes difficult to tell the speakers apart`
`        00:00:01.045 - 00:00:05.473`

`G021   I don't know where my backpack is [screams] . did you take my backpack ?`
`        00:00:06.023 - 00:00:10.549`

(Speaker code)(Four spaces)(Transcription)
(Eight spaces)(Timestamp)

**Comment by Gabrielsonnn** [comment]
ahh i see thank you
