### ISSUE TITLE
Reading transcriptions on multiple lines

### ISSUE THREAD

**Issue by allyugalde** [Gabrielsonnn/Intervocalic-t-Search#8]
The following is an example of multi-line transcriptions. The "_"s are used instead of spaces as multiple spaces are deleted and shortened to single spaces by GitHub. Full words stay on the same line, although bracketed sections can span multiple lines.

`M001___hey how was school today ? did you [B001`
`_______sneezes] have music class today ? . `
`_______00:23:05.125 - 00:23:25.150`
` `
`B001___we went to the park for gym and then`
`_______we learned about the dinosaurs that`
`_______eat plants only and then . and th-- {somebody`
`_______running in the background} then we wen--`
`_______00:23:25.652 - 00:23:49.945`
` `
`M001___herbivores ? . if they eat plants then `
`_______they're called herbivores . did you learn`
`_______that in school ?`
`_______00:23:48.125 - 00:24:07.150`

**Comment by Gabrielsonnn** [comment]
NOTE: father or notes could be on two lines aswell
